name: Terraform EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  terraform-plan:

    runs-on: terraform-host

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:

    needs: terraform-plan
    runs-on: terraform-host

    environment: production   # 👈 manual approval happens here

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve